# Generated by Django 2.1.7 on 2019-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок статьи')),
                ('text', models.TextField(max_length=5000, verbose_name='Содержание')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.TextField(max_length=100, verbose_name='Автор статьи')),
            ],
        ),
    ]
